# Dependencies
markdown:         kramdown
highlighter:      Rouge

# Permalinks
permalink:        pretty

# Setup
title:            Gajesh
tagline:          "Software Engineer"
description:      "I am Software Engineer who likes to read,write and learn."
url:              ""
baseurl:          "/"

author:
  name:           'Gajesh Bhat'
  url:            https://twitter.com/gajeshbht

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/gajeshbhat

blog:
  blogroll:       "archive.html"

plugins:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet